logging:
  level:
    root: DEBUG
spring:
  application:
    name: auth_service
  data:
    mongodb:
      uri: mongodb+srv://jack:jack%40123@jack-it.fqjnlrv.mongodb.net/
      database: jack-it
jwt:
  ttl: 30s
  issuer: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

